name: mediamaster
description: "MediaMaster"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http            : ^1.2.1
  html            : ^0.15.4
  hive            : ^2.2.3
  pair            : ^0.1.2
  intl            : ^0.19.0
  path            : ^1.9.0
  shelf           : ^1.4.1
  dotenv          : ^4.2.0
  numerus         : ^2.3.0
  supabase        : ^2.6.0
  ansicolor       : ^2.0.3
  puppeteer       : ^3.15.0
  equatable       : ^2.0.3
  shelf_plus      : ^1.10.0
  basic_utils     : ^5.7.0
  dart_console    : ^4.0.1
  hive_flutter    : ^1.1.0
  shelf_router    : ^1.1.4
  shelf_static    : ^1.1.3
  flutter_bloc    : ^8.1.6
  axios_package   : ^0.0.3
  hive_generator  : ^2.0.1
  email_validator : ^3.0.0
  adaptive_theme  : ^3.4.0
  cupertino_icons : ^1.0.6
  shelf_hotreload : ^1.5.0
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  test         : ^1.24.9
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
  uses-material-design: true

scripts:
  restore             : flutter clean && flutter pub get
  app                 : flutter run -d windows
  app:dev             : flutter run -d windows --release
  app:local           : flutter run --dart-define=LOCAL=true -d windows
  dummy               : dart --define=LOCAL=true lib\Dummy.dart
  lint                : flutter analyze
  server              : dart run --define=LOCAL=true backend/main.dart
  server:dev          : dart run --define=RELOAD=true --define=LOCAL=true --enable-vm-service backend/main.dart
  server:node         : nodemon -x "dart run --define=LOCAL=true backend/main.dart" -e dart
  deploy              : fly deploy
  cli                 : dart backend/providers/cli.dart
  test:steam          : dart --define=LOCAL=true test/providers/steam_test.dart
  test:igdb           : dart --define=LOCAL=true test/providers/igdb_test.dart
  test:hltb           : dart --define=LOCAL=true test/providers/hltb_test.dart
  test:pcgw           : dart --define=LOCAL=true test/providers/pcgw_test.dart
  test:goodreads      : dart --define=LOCAL=true test/providers/goodreads_test.dart
  test:tmdb           : dart --define=LOCAL=true test/providers/tmdb_test.dart
  test:anilist        : dart --define=LOCAL=true test/providers/anilist_test.dart
  test:providers      : dart test/providers/run_tests.dart
  test:anime          : dart --define=LOCAL=true test/resources/anime_test.dart
  test:appachievement : dart --define=LOCAL=true test/resources/app_achievement_test.dart
  test:book           : dart --define=LOCAL=true test/resources/book_test.dart
  test:creator        : dart --define=LOCAL=true test/resources/creator_test.dart
  test:game           : dart --define=LOCAL=true test/resources/game_test.dart
  test:gameachievement: dart --define=LOCAL=true test/resources/game_achievement_test.dart
  test:genre          : dart --define=LOCAL=true test/resources/genre_test.dart
  test:link           : dart --define=LOCAL=true test/resources/link_test.dart
  test:manga          : dart --define=LOCAL=true test/resources/manga_test.dart
  test:media          : dart --define=LOCAL=true test/resources/media_test.dart
  test:mediacreator   : dart --define=LOCAL=true test/resources/media_creator_test.dart
  test:medialink      : dart --define=LOCAL=true test/resources/media_link_test.dart
  test:mediaplatform  : dart --define=LOCAL=true test/resources/media_platform_test.dart
  test:mediapublisher : dart --define=LOCAL=true test/resources/media_publisher_test.dart
  test:mediaretailer  : dart --define=LOCAL=true test/resources/media_retailer_test.dart
  test:mediaseries    : dart --define=LOCAL=true test/resources/media_series_test.dart
  test:mediauser      : dart --define=LOCAL=true test/resources/media_user_test.dart
  test:mediausergenre : dart --define=LOCAL=true test/resources/media_user_genre_test.dart
  test:mediausertag   : dart --define=LOCAL=true test/resources/media_user_tag_test.dart
  test:movie          : dart --define=LOCAL=true test/resources/movie_test.dart
  test:note           : dart --define=LOCAL=true test/resources/note_test.dart
  test:platform       : dart --define=LOCAL=true test/resources/platform_test.dart
  test:publisher      : dart --define=LOCAL=true test/resources/publisher_test.dart
  test:retailer       : dart --define=LOCAL=true test/resources/retailer_test.dart
  test:season         : dart --define=LOCAL=true test/resources/season_test.dart
  test:series         : dart --define=LOCAL=true test/resources/series_test.dart
  test:tag            : dart --define=LOCAL=true test/resources/tag_test.dart
  test:tv_series      : dart --define=LOCAL=true test/resources/tv_series_test.dart
  test:userachievement: dart --define=LOCAL=true test/resources/user_achievement_test.dart
  test:wishlist       : dart --define=LOCAL=true test/resources/wishlist_test.dart
  test:resources      : dart test/resources/run_tests.dart
